{
 "title": "Proxy status",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "10s",
 "panels": [
  { "title": "Proxy status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CPU Count",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "scrapoxy_proxy_dispatcher_cpu_count",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Number of proxies",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 3, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "scrapoxy_proxy_dispatcher_proxy_count{removing=\"false\"}",
     "legendFormat": "{{removing}}"
    }
   ]
  },
  {
   "title": "Proxies status",
   "type": "stat",
   "gridPos": { "h": 4, "w": 17, "x": 7, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "scrapoxy_proxy_dispatcher_proxy_status",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "scrapoxy_fingerprint_server_mem_sys_total",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Proxy status",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 21, "x": 3, "y": 5 },
   "targets": [
    {
     "expr": "scrapoxy_proxy_dispatcher_proxy_status",
     "legendFormat": "{{status}}"
    }
   ]
  },
  { "title": "Server status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "rate(scrapoxy_fingerprint_server_cpu_usage_system[$__rate_interval])",
     "legendFormat": "system"
    },
    {
     "expr": "rate(scrapoxy_fingerprint_server_cpu_usage_user[$__rate_interval])",
     "legendFormat": "User"
    },
    {
     "expr": "rate(scrapoxy_fingerprint_server_cpu_usage_nice[$__rate_interval])",
     "legendFormat": "Nice"
    },
    {
     "expr": "rate(scrapoxy_fingerprint_server_cpu_usage_wait[$__rate_interval])",
     "legendFormat": "Wait"
    },
    {
     "expr": "rate(scrapoxy_fingerprint_server_cpu_usage_idle[$__rate_interval])",
     "legendFormat": "Idle"
    }
   ]
  },
  {
   "title": "Memory usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "scrapoxy_fingerprint_server_mem_sys_used",
     "legendFormat": "Used"
    },
    {
     "expr": "scrapoxy_fingerprint_server_mem_sys_free",
     "legendFormat": "Free"
    }
   ]
  },
  {
   "title": "Load Average",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 10 },
   "targets": [
    {
     "expr": "scrapoxy_fingerprint_server_cpu_load_one",
     "legendFormat": "One"
    },
    {
     "expr": "scrapoxy_fingerprint_server_cpu_load_five",
     "legendFormat": "Five"
    },
    {
     "expr": "scrapoxy_fingerprint_server_cpu_load_fifteen",
     "legendFormat": "Fifteen"
    }
   ]
  },
  { "title": "Requests", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "Requests",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "rate(scrapoxy_proxy_dispatcher_requests_count[$__rate_interval])",
     "legendFormat": "Requests"
    }
   ]
  },
  {
   "title": "Error count",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 19 },
   "targets": [
    {
     "expr": "rate(scrapoxy_proxy_dispatcher_errors_count[$__rate_interval])",
     "legendFormat": "Error count"
    }
   ]
  },
  {
   "title": "Bytes sent and received",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "rate(scrapoxy_proxy_dispatcher_bytes_received[$__rate_interval])",
     "legendFormat": "Bytes received"
    },
    {
     "expr": "rate(scrapoxy_proxy_dispatcher_bytes_sent[$__rate_interval])",
     "legendFormat": "Bytes sent"
    }
   ]
  },
  {
   "title": "Proxy Dispatcher memory stats",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 },
   "collapsed": true,
   "panels": [
    {
     "title": "Memory utilisation",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 35 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "scrapoxy_proxy_dispatcher_mem_alloc",
       "legendFormat": "scrapoxy_proxy_dispatcher_mem_alloc"
      },
      {
       "expr": "scrapoxy_proxy_dispatcher_mem_heap_alloc",
       "legendFormat": "scrapoxy_proxy_dispatcher_mem_heap_alloc"
      },
      {
       "expr": "scrapoxy_proxy_dispatcher_mem_stack_inuse",
       "legendFormat": "scrapoxy_proxy_dispatcher_mem_stack_inuse"
      }
     ]
    },
    {
     "title": "Memory stats",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 42 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "scrapoxy_proxy_dispatcher_mem_heap_alloc",
       "legendFormat": "scrapoxy_proxy_dispatcher_mem_heap_alloc"
      },
      {
       "expr": "scrapoxy_proxy_dispatcher_mem_heap_idle",
       "legendFormat": "scrapoxy_proxy_dispatcher_mem_heap_idle"
      },
      {
       "expr": "scrapoxy_proxy_dispatcher_mem_heap_inuse",
       "legendFormat": "scrapoxy_proxy_dispatcher_mem_heap_inuse"
      }
     ]
    },
    {
     "title": "Stack size",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 42 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "scrapoxy_proxy_dispatcher_mem_stack_inuse",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Go Routine count",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 50 },
     "targets": [
      {
       "expr": "scrapoxy_proxy_dispatcher_goroutine_count",
       "legendFormat": "goroutine_count"
      }
     ]
    },
    {
     "title": "Garbage Collector count",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 50 },
     "targets": [
      {
       "expr": "scrapoxy_proxy_dispatcher_mem_gc_count",
       "legendFormat": "scrapoxy_proxy_dispatcher_mem_gc_count"
      }
     ]
    }
   ]
  }
 ]
}